# Generated by Django 4.2.4 on 2023-08-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comments_counts_alter_post_created_at_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comments_counts',
            new_name='comments_count',
        ),
    ]
